# 文字ラベルの出力先ディレクトリ
output_directory: ..\resources\labels

# 文字情報を新規作成するか
# - is_new_create(False) の場合には output_directory ディレクトリに保存されている文字情報の読込を試みます。
#   読み込みに失敗した場合には自動的に新規作成フローで進行します。
is_new_create: True

# フォントパス
font_path: ..\resources\fonts\SourceHanSans\SourceHanSans-Bold.otf

# 識字から除外する文字
# - 異体字を識字から除外させるべきかは検討中です。
#   現状は異体字から正字変換機能を用意して対応しています。
ignore_characters: [
  # 亅部は、漢字を部首により分類したグループの一つ。
  亅,
  # 丨部は、漢字を部首により分類したグループの一つ。
  丨,
  # 丿部は、漢字を部首により分類したグループの一つ。
  丿,
  # 丶部は、漢字を部首によって分類したグループの一つ。
  丶,
  # 厶部は、漢字を部首により分類したグループの1つ。
  厶,
  # 卜部（ぼくぶ）は、漢字を部首により分類したグループの一つ。
  卜,
  # 囗部（いぶ）は、漢字を部首により分類したグループの一つ。
  囗,
  # 昻は、昂の異体字
  昻,
  # 瞹は、曖の異体字
  瞹,
  # 况は、況の異体字
  况,
  # 决は、決の異体字
  决,
  # 內は、内（新字体）の異体字（旧字体）
  內,
  # 戶は、戸（新字体）の異体字（旧字体）
  戶,
  # 册は、冊（新字体）の異体字（旧字体）
  册,
  # 收は、収（新字体）の異体字（旧字体）
  收,
  # 羽は、羽（新字体）の異体字（旧字体）
  羽,
  # 吳は、呉（新字体）の異体字（旧字体）
  吳,
  # 吿は、告（新字体）の異体字（旧字体）
  吿,
  # 佛は、仏（新字体）の異体字（旧字体）
  佛,
  # 免は、免（新字体）の異体字（旧字体）
  免,
  # 每は、毎（新字体）の異体字（旧字体）
  每,
  # 步は、歩（新字体）の異体字（旧字体）
  步,
  # 壯は、壮（新字体）の異体字（旧字体）
  壯,
  # 沒は、没（新字体）の異体字（旧字体）
  沒,
  # 狀は、状（新字体）の異体字（旧字体）
  狀,
  # 社は、社（新字体）の異体字（旧字体）
  社,
  # 靑は、青（新字体）の異体字（旧字体）
  靑,
  # 屆は、届（新字体）の異体字（旧字体）
  屆,
  # 卷は、巻（新字体）の異体字（旧字体）
  卷,
  # 兒は、児（新字体）の異体字（旧字体）
  兒,
  # 兩は、両（新字体）の異体字（旧字体）
  兩,
  # 戾は、戻（新字体）の異体字（旧字体）
  戾,
  # 拂は、払（新字体）の異体字（旧字体）
  拂,
  # 拔は、抜（新字体）の異体字（旧字体）
  拔,
  # 尙は、尚（新字体）の異体字（旧字体）
  尙,
  # 卑は、卑（新字体）の異体字（旧字体）
  卑,
  # 亞は、亜（新字体）の異体字（旧字体）
  亞,
  # 來は、来（新字体）の異体字（旧字体）
  來,
  # 爭は、争（新字体）の異体字（旧字体）
  爭,
  # 舍は、舎（新字体）の異体字（旧字体）
  舍,
  # 卽は、即（新字体）の異体字（旧字体）
  卽,
  # 祈は、祈（新字体）の異体字（旧字体）
  祈,
  # 勉は、勉（新字体）の異体字（旧字体）
  勉,
  # 突は、突（新字体）の異体字（旧字体）
  突,
  # 者は、者（新字体）の異体字（旧字体）
  者,
  # 恆は、恒（新字体）の異体字（旧字体）
  恆,
  # 祉は、祉（新字体）の異体字（旧字体）
  祉,
  # 侮は、侮（新字体）の異体字（旧字体）
  侮,
  # 拜は、拝（新字体）の異体字（旧字体）
  拜,
  # 眞は、真（新字体）の異体字（旧字体）
  眞,
  # 氣は、気（新字体）の異体字（旧字体）
  氣,
  # 臭は、臭（新字体）の異体字（旧字体）
  臭,
  # 郞は、郎（新字体）の異体字（旧字体）
  郞,
  # 狹は、狭（新字体）の異体字（旧字体）
  狹,
  # 海は、海（新字体）の異体字（旧字体）
  海,
  # 峽は、峡（新字体）の異体字（旧字体）
  峽,
  # 莖は、茎（新字体）の異体字（旧字体）
  莖,
  # 徑は、径（新字体）の異体字（旧字体）
  徑,
  # 缺は、欠（新字体）の異体字（旧字体）
  缺,
  # 悔は、悔（新字体）の異体字（旧字体）
  悔,
  # 倂は、併（新字体）の異体字（旧字体）
  倂,
  # 莊は、荘（新字体）の異体字（旧字体）
  莊,
  # 乘は、乗（新字体）の異体字（旧字体）
  乘,
  # 竝は、並（新字体）の異体字（旧字体）
  竝,
  # 悅は、悦（新字体）の異体字（旧字体）
  悅,
  # 晉は、晋（新字体）の異体字（旧字体）
  晉,
  # 益は、益（新字体）の異体字（旧字体）
  益,
  # 祐は、祐（新字体）の異体字（旧字体）
  祐,
  # 祖は、祖（新字体）の異体字（旧字体）
  祖,
  # 祝は、祝（新字体）の異体字（旧字体）
  祝,
  # 娛は、娯（新字体）の異体字（旧字体）
  娛,
  # 神は、神（新字体）の異体字（旧字体）
  神,
  # 祕は、秘（新字体）の異体字（旧字体）
  祕,
  # 效は、効（新字体）の異体字（旧字体）
  效,
  # 挾は、挟（新字体）の異体字（旧字体）
  挾,
  # 涉は、渉（新字体）の異体字（旧字体）
  涉,
  # 麥は、麦（新字体）の異体字（旧字体）
  麥,
  # 淺は、浅（新字体）の異体字（旧字体）
  淺,
  # 淨は、浄（新字体）の異体字（旧字体）
  淨,
  # 敏は、敏（新字体）の異体字（旧字体）
  敏,
  # 條は、条（新字体）の異体字（旧字体）
  # NOTE: オトメスマイルの人名で使用する
  # 條,
  # 祥は、祥（新字体）の異体字（旧字体）
  祥,
  # 帶は、帯（新字体）の異体字（旧字体）
  帶,
  # 參は、参（新字体）の異体字（旧字体）
  參,
  # 連は、連（新字体）の異体字（旧字体）
  連,
  # 假は、仮（新字体）の異体字（旧字体）
  假,
  # 區は、区（新字体）の異体字（旧字体）
  區,
  # 殺は、殺（新字体）の異体字（旧字体）
  殺,
  # 晝は、昼（新字体）の異体字（旧字体）
  晝,
  # 脫は、脱（新字体）の異体字（旧字体）
  脫,
  # 敎は、教（新字体）の異体字（旧字体）
  敎,
  # 硏は、研（新字体）の異体字（旧字体）
  硏,
  # 產は、産（新字体）の異体字（旧字体）
  產,
  # 敍は、叙（新字体）の異体字（旧字体）
  敍,
  # 陷は、陥（新字体）の異体字（旧字体）
  陷,
  # 敕は、勅（新字体）の異体字（旧字体）
  敕,
  # 圈は、圏（新字体）の異体字（旧字体）
  圈,
  # 專は、専（新字体）の異体字（旧字体）
  專,
  # 朗は、朗（新字体）の異体字（旧字体）
  朗,
  # 將は、将（新字体）の異体字（旧字体）
  將,
  # 巢は、巣（新字体）の異体字（旧字体）
  巢,
  # 處は、処（新字体）の異体字（旧字体）
  處,
  # 晚は、晩（新字体）の異体字（旧字体）
  晚,
  # 國は、国（新字体）の異体字（旧字体）
  國,
  # 淚は、涙（新字体）の異体字（旧字体）
  淚,
  # 從は、従（新字体）の異体字（旧字体）
  從,
  # 棧は、桟（新字体）の異体字（旧字体）
  棧,
  # 搜は、捜（新字体）の異体字（旧字体）
  搜,
  # 惱は、悩（新字体）の異体字（旧字体）
  惱,
  # 殼は、殻（新字体）の異体字（旧字体）
  殼,
  # 都は、都（新字体）の異体字（旧字体）
  都,
  # 爲は、為（新字体）の異体字（旧字体）
  爲,
  # 猪は、猪（新字体）の異体字（旧字体）
  猪,
  # 畫は、画（新字体）の異体字（旧字体）
  畫,
  # 剩は、剰（新字体）の異体字（旧字体）
  剩,
  # 壻は、婿（新字体）の異体字（旧字体）
  壻,
  # 插は、挿（新字体）の異体字（旧字体）
  插,
  # 盜は、盗（新字体）の異体字（旧字体）
  盜,
  # 黑は、黒（新字体）の異体字（旧字体）
  黑,
  # 曾は、曽（新字体）の異体字（旧字体）
  曾,
  # 勞は、労（新字体）の異体字（旧字体）
  勞,
  # 喝は、喝（新字体）の異体字（旧字体）
  喝,
  # 晴は、晴（新字体）の異体字（旧字体）
  晴,
  # 發は、発（新字体）の異体字（旧字体）
  發,
  # 稅は、税（新字体）の異体字（旧字体）
  稅,
  # 單は、単（新字体）の異体字（旧字体）
  單,
  # 黃は、黄（新字体）の異体字（旧字体）
  黃,
  # 堯は、尭（新字体）の異体字（旧字体）
  堯,
  # 虛は、虚（新字体）の異体字（旧字体）
  虛,
  # 惠は、恵（新字体）の異体字（旧字体）
  惠,
  # 圍は、囲（新字体）の異体字（旧字体）
  圍,
  # 揭は、掲（新字体）の異体字（旧字体）
  揭,
  # 壹は、壱（新字体）の異体字（旧字体）
  壹,
  # 渴は、渇（新字体）の異体字（旧字体）
  渴,
  # 著は、著（新字体）の異体字（旧字体）
  著,
  # 惡は、悪（新字体）の異体字（旧字体）
  惡,
  # 視は、視（新字体）の異体字（旧字体）
  視,
  # 琢は、琢（新字体）の異体字（旧字体）
  琢,
  # 渚は、渚（新字体）の異体字（旧字体）
  渚,
  # 絲は、糸（新字体）の異体字（旧字体）
  絲,
  # 逸は、逸（新字体）の異体字（旧字体）
  逸,
  # 殘は、残（新字体）の異体字（旧字体）
  殘,
  # 貳は、弐（新字体）の異体字（旧字体）
  貳,
  # 萬は、万（新字体）の異体字（旧字体）
  萬,
  # 腦は、脳（新字体）の異体字（旧字体）
  腦,
  # 與は、与（新字体）の異体字（旧字体）
  與,
  # 肅は、粛（新字体）の異体字（旧字体）
  肅,
  # 祿は、禄（新字体）の異体字（旧字体）
  祿,
  # 碎は、砕（新字体）の異体字（旧字体）
  碎,
  # 溪は、渓（新字体）の異体字（旧字体）
  溪,
  # 傳は、伝（新字体）の異体字（旧字体）
  傳,
  # 會は、会（新字体）の異体字（旧字体）
  會,
  # 愼は、慎（新字体）の異体字（旧字体）
  愼,
  # 亂は、乱（新字体）の異体字（旧字体）
  亂,
  # 當は、当（新字体）の異体字（旧字体）
  當,
  # 裝は、装（新字体）の異体字（旧字体）
  裝,
  # 經は、経（新字体）の異体字（旧字体）
  經,
  # 搖は、揺（新字体）の異体字（旧字体）
  搖,
  # 圓は、円（新字体）の異体字（旧字体）
  圓,
  # 奧は、奥（新字体）の異体字（旧字体）
  奧,
  # 飮は、飲（新字体）の異体字（旧字体）
  飮,
  # 號は、号（新字体）の異体字（旧字体）
  號,
  # 廉は、廉（新字体）の異体字（旧字体）
  廉,
  # 廊は、廊（新字体）の異体字（旧字体）
  廊,
  # 虜は、虜（新字体）の異体字（旧字体）
  虜,
  # 溫は、温（新字体）の異体字（旧字体）
  溫,
  # 碑は、碑（新字体）の異体字（旧字体）
  碑,
  # 煮は、煮（新字体）の異体字（旧字体）
  煮,
  # 暑は、暑（新字体）の異体字（旧字体）
  暑,
  # 鄕は、郷（新字体）の異体字（旧字体）
  鄕,
  # 甁は、瓶（新字体）の異体字（旧字体）
  甁,
  # 塚は、塚（新字体）の異体字（旧字体）
  塚,
  # 歲は、歳（新字体）の異体字（旧字体）
  歲,
  # 勤は、勤（新字体）の異体字（旧字体）
  勤,
  # 靖は、靖（新字体）の異体字（旧字体）
  靖,
  # 飯は、飯（新字体）の異体字（旧字体）
  飯,
  # 壽は、寿（新字体）の異体字（旧字体）
  壽,
  # 寢は、寝（新字体）の異体字（旧字体）
  寢,
  # 圖は、図（新字体）の異体字（旧字体）
  圖,
  # 寬は、寛（新字体）の異体字（旧字体）
  寬,
  # 賓は、賓（新字体）の異体字（旧字体）
  賓,
  # 署は、署（新字体）の異体字（旧字体）
  署,
  # 禍は、禍（新字体）の異体字（旧字体）
  禍,
  # 稱は、称（新字体）の異体字（旧字体）
  稱,
  # 福は、福（新字体）の異体字（旧字体）
  福,
  # 漢は、漢（新字体）の異体字（旧字体）
  漢,
  # 盡は、尽（新字体）の異体字（旧字体）
  盡,
  # 嘆は、嘆（新字体）の異体字（旧字体）
  嘆,
  # 團は、団（新字体）の異体字（旧字体）
  團,
  # 輕は、軽（新字体）の異体字（旧字体）
  輕,
  # 僧は、僧（新字体）の異体字（旧字体）
  僧,
  # 綠は、緑（新字体）の異体字（旧字体）
  綠,
  # 遞は、逓（新字体）の異体字（旧字体）
  遞,
  # 對は、対（新字体）の異体字（旧字体）
  對,
  # 粹は、粋（新字体）の異体字（旧字体）
  粹,
  # 禎は、禎（新字体）の異体字（旧字体）
  禎,
  # 慘は、惨（新字体）の異体字（旧字体）
  慘,
  # 遙は、遥（新字体）の異体字（旧字体）
  遙,
  # 蓮は、蓮（新字体）の異体字（旧字体）
  蓮,
  # 塀は、塀（新字体）の異体字（旧字体）
  塀,
  # 飼は、飼（新字体）の異体字（旧字体）
  飼,
  # 精は、精（新字体）の異体字（旧字体）
  精,
  # 臺は、台（新字体）の異体字（旧字体）
  臺,
  # 槇は、槙（新字体）の異体字（旧字体）
  槇,
  # 瑤は、瑶（新字体）の異体字（旧字体）
  瑤,
  # 榮は、栄（新字体）の異体字（旧字体）
  榮,
  # 實は、実（新字体）の異体字（旧字体）
  實,
  # 褐は、褐（新字体）の異体字（旧字体）
  褐,
  # 奬は、奨（新字体）の異体字（旧字体）
  奬,
  # 滿は、満（新字体）の異体字（旧字体）
  滿,
  # 齊は、斉（新字体）の異体字（旧字体）
  齊,
  # 僞は、偽（新字体）の異体字（旧字体）
  僞,
  # 滯は、滞（新字体）の異体字（旧字体）
  滯,
  # 練は、練（新字体）の異体字（旧字体）
  練,
  # 樂は、楽（新字体）の異体字（旧字体）
  樂,
  # 儉は、倹（新字体）の異体字（旧字体）
  儉,
  # 寫は、写（新字体）の異体字（旧字体）
  寫,
  # 齒は、歯（新字体）の異体字（旧字体）
  齒,
  # 踐は、践（新字体）の異体字（旧字体）
  踐,
  # 稻は、稲（新字体）の異体字（旧字体）
  稻,
  # 德は、徳（新字体）の異体字（旧字体）
  德,
  # 緖は、緒（新字体）の異体字（旧字体）
  緖,
  # 增は、増（新字体）の異体字（旧字体）
  增,
  # 墨は、墨（新字体）の異体字（旧字体）
  墨,
  # 劍は、剣（新字体）の異体字（旧字体）
  劍,
  # 層は、層（新字体）の異体字（旧字体）
  層,
  # 節は、節（新字体）の異体字（旧字体）
  節,
  # 彈は、弾（新字体）の異体字（旧字体）
  彈,
  # 憎は、憎（新字体）の異体字（旧字体）
  憎,
  # 墮は、堕（新字体）の異体字（旧字体）
  墮,
  # 舖は、舗（新字体）の異体字（旧字体）
  舖,
  # 緣は、縁（新字体）の異体字（旧字体）
  緣,
  # 價は、価（新字体）の異体字（旧字体）
  價,
  # 瘦は、痩（新字体）の異体字（旧字体）
  瘦,
  # 徵は、徴（新字体）の異体字（旧字体）
  徵,
  # 樓は、楼（新字体）の異体字（旧字体）
  樓,
  # 樣は、様（新字体）の異体字（旧字体）
  樣,
  # 樞は、枢（新字体）の異体字（旧字体）
  樞,
  # 穀は、穀（新字体）の異体字（旧字体）
  穀,
  # 澁は、渋（新字体）の異体字（旧字体）
  澁,
  # 廚は、厨（新字体）の異体字（旧字体）
  廚,
  # 廣は、広（新字体）の異体字（旧字体）
  廣,
  # 歐は、欧（新字体）の異体字（旧字体）
  歐,
  # 賣は、売（新字体）の異体字（旧字体）
  賣,
  # 廢は、廃（新字体）の異体字（旧字体）
  廢,
  # 髮は、髪（新字体）の異体字（旧字体）
  髮,
  # 毆は、殴（新字体）の異体字（旧字体）
  毆,
  # 數は、数（新字体）の異体字（旧字体）
  數,
  # 醉は、酔（新字体）の異体字（旧字体）
  醉,
  # 隨は、随（新字体）の異体字（旧字体）
  隨,
  # 賴は、頼（新字体）の異体字（旧字体）
  賴,
  # 縣は、県（新字体）の異体字（旧字体）
  縣,
  # 擔は、担（新字体）の異体字（旧字体）
  擔,
  # 澤は、沢（新字体）の異体字（旧字体）
  # NOTE: D.C.4の人名で使用する
  # 澤,
  # 歷は、歴（新字体）の異体字（旧字体）
  歷,
  # 戰は、戦（新字体）の異体字（旧字体）
  戰,
  # 曆は、暦（新字体）の異体字（旧字体）
  曆,
  # 燒は、焼（新字体）の異体字（旧字体）
  燒,
  # 擇は、択（新字体）の異体字（旧字体）
  擇,
  # 餘は、余（新字体）の異体字（旧字体）
  餘,
  # 靜は、静（新字体）の異体字（旧字体）
  靜,
  # 默は、黙（新字体）の異体字（旧字体）
  默,
  # 謁は、謁（新字体）の異体字（旧字体）
  謁,
  # 勵は、励（新字体）の異体字（旧字体）
  勵,
  # 橫は、横（新字体）の異体字（旧字体）
  橫,
  # 據は、拠（新字体）の異体字（旧字体）
  據,
  # 錢は、銭（新字体）の異体字（旧字体）
  錢,
  # 勳は、勲（新字体）の異体字（旧字体）
  勳,
  # 險は、険（新字体）の異体字（旧字体）
  險,
  # 錄は、録（新字体）の異体字（旧字体）
  錄,
  # 學は、学（新字体）の異体字（旧字体）
  學,
  # 獨は、独（新字体）の異体字（旧字体）
  獨,
  # 曉は、暁（新字体）の異体字（旧字体）
  曉,
  # 螢は、蛍（新字体）の異体字（旧字体）
  螢,
  # 龍は、竜（新字体）の異体字（旧字体）
  龍,
  # 燈は、灯（新字体）の異体字（旧字体）
  燈,
  # 諸は、諸（新字体）の異体字（旧字体）
  諸,
  # 龜は、亀（新字体）の異体字（旧字体）
  龜,
  # 器は、器（新字体）の異体字（旧字体）
  器,
  # 衞は、衛（新字体）の異体字（旧字体）
  衞,
  # 辨は、弁（新字体）の異体字（旧字体）
  辨,
  # 劑は、剤（新字体）の異体字（旧字体）
  劑,
  # 頻は、頻（新字体）の異体字（旧字体）
  頻,
  # 豫は、予（新字体）の異体字（旧字体）
  豫,
  # 遲は、遅（新字体）の異体字（旧字体）
  遲,
  # 館は、館（新字体）の異体字（旧字体）
  館,
  # 總は、総（新字体）の異体字（旧字体）
  總,
  # 檢は、検（新字体）の異体字（旧字体）
  檢,
  # 舊は、旧（新字体）の異体字（旧字体）
  舊,
  # 嶽は、岳（新字体）の異体字（旧字体）
  嶽,
  # 濕は、湿（新字体）の異体字（旧字体）
  濕,
  # 點は、点（新字体）の異体字（旧字体）
  點,
  # 餠は、餅（新字体）の異体字（旧字体）
  餠,
  # 謠は、謡（新字体）の異体字（旧字体）
  謠,
  # 膽は、胆（新字体）の異体字（旧字体）
  膽,
  # 潛は、潜（新字体）の異体字（旧字体）
  潛,
  # 薰は、薫（新字体）の異体字（旧字体）
  薰,
  # 聰は、聡（新字体）の異体字（旧字体）
  聰,
  # 擊は、撃（新字体）の異体字（旧字体）
  擊,
  # 聲は、声（新字体）の異体字（旧字体）
  聲,
  # 濱は、浜（新字体）の異体字（旧字体）
  濱,
  # 鍊は、錬（新字体）の異体字（旧字体）
  鍊,
  # 應は、応（新字体）の異体字（旧字体）
  應,
  # 穗は、穂（新字体）の異体字（旧字体）
  穗,
  # 縱は、縦（新字体）の異体字（旧字体）
  縱,
  # 繁は、繁（新字体）の異体字（旧字体）
  繁,
  # 戲は、戯（新字体）の異体字（旧字体）
  戲,
  # 彌は、弥（新字体）の異体字（旧字体）
  彌,
  # 襃は、褒（新字体）の異体字（旧字体）
  襃,
  # 營は、営（新字体）の異体字（旧字体）
  營,
  # 禪は、禅（新字体）の異体字（旧字体）
  禪,
  # 濟は、済（新字体）の異体字（旧字体）
  濟,
  # 壓は、圧（新字体）の異体字（旧字体）
  壓,
  # 擧は、挙（新字体）の異体字（旧字体）
  擧,
  # 隸は、隷（新字体）の異体字（旧字体）
  隸,
  # 齋は、斎（新字体）の異体字（旧字体）
  齋,
  # 隱は、隠（新字体）の異体字（旧字体）
  隱,
  # 雙は、双（新字体）の異体字（旧字体）
  雙,
  # 禮は、礼（新字体）の異体字（旧字体）
  禮,
  # 雜は、雑（新字体）の異体字（旧字体）
  雜,
  # 藥は、薬（新字体）の異体字（旧字体）
  藥,
  # 藝は、芸（新字体）の異体字（旧字体）
  藝,
  # 顏は、顔（新字体）の異体字（旧字体）
  顏,
  # 鎭は、鎮（新字体）の異体字（旧字体）
  鎭,
  # 豐は、豊（新字体）の異体字（旧字体）
  豐,
  # 藏は、蔵（新字体）の異体字（旧字体）
  藏,
  # 轉は、転（新字体）の異体字（旧字体）
  轉,
  # 歸は、帰（新字体）の異体字（旧字体）
  歸,
  # 擴は、拡（新字体）の異体字（旧字体）
  擴,
  # 壘は、塁（新字体）の異体字（旧字体）
  壘,
  # 醫は、医（新字体）の異体字（旧字体）
  醫,
  # 謹は、謹（新字体）の異体字（旧字体）
  謹,
  # 蟲は、虫（新字体）の異体字（旧字体）
  蟲,
  # 獵は、猟（新字体）の異体字（旧字体）
  獵,
  # 斷は、断（新字体）の異体字（旧字体）
  斷,
  # 壞は、壊（新字体）の異体字（旧字体）
  壞,
  # 穩は、穏（新字体）の異体字（旧字体）
  穩,
  # 瀧は、滝（新字体）の異体字（旧字体）
  瀧,
  # 證は、証（新字体）の異体字（旧字体）
  證,
  # 懷は、懐（新字体）の異体字（旧字体）
  懷,
  # 類は、類（新字体）の異体字（旧字体）
  類,
  # 繪は、絵（新字体）の異体字（旧字体）
  繪,
  # 懲は、懲（新字体）の異体字（旧字体）
  懲,
  # 贊は、賛（新字体）の異体字（旧字体）
  贊,
  # 繩は、縄（新字体）の異体字（旧字体）
  繩,
  # 癡は、痴（新字体）の異体字（旧字体）
  癡,
  # 邊は、辺（新字体）の異体字（旧字体）
  邊,
  # 勸は、勧（新字体）の異体字（旧字体）
  勸,
  # 關は、関（新字体）の異体字（旧字体）
  關,
  # 瀨は、瀬（新字体）の異体字（旧字体）
  瀨,
  # 贈は、贈（新字体）の異体字（旧字体）
  贈,
  # 難は、難（新字体）の異体字（旧字体）
  難,
  # 辭は、辞（新字体）の異体字（旧字体）
  辭,
  # 獸は、獣（新字体）の異体字（旧字体）
  獸,
  # 鬪は、闘（新字体）の異体字（旧字体）
  鬪,
  # 孃は、嬢（新字体）の異体字（旧字体）
  孃,
  # 獻は、献（新字体）の異体字（旧字体）
  獻,
  # 爐は、炉（新字体）の異体字（旧字体）
  爐,
  # 譯は、訳（新字体）の異体字（旧字体）
  譯,
  # 觸は、触（新字体）の異体字（旧字体）
  觸,
  # 麵は、麺（新字体）の異体字（旧字体）
  麵,
  # 寶は、宝（新字体）の異体字（旧字体）
  寶,
  # 蘭は、蘭（新字体）の異体字（旧字体）
  蘭,
  # 瓣は、弁（新字体）の異体字（旧字体）
  瓣,
  # 釋は、釈（新字体）の異体字（旧字体）
  釋,
  # 嚴は、厳（新字体）の異体字（旧字体）
  嚴,
  # 譽は、誉（新字体）の異体字（旧字体）
  譽,
  # 黨は、党（新字体）の異体字（旧字体）
  黨,
  # 壤は、壌（新字体）の異体字（旧字体）
  壤,
  # 騷は、騒（新字体）の異体字（旧字体）
  騷,
  # 繼は、継（新字体）の異体字（旧字体）
  繼,
  # 齡は、齢（新字体）の異体字（旧字体）
  齡,
  # 犧は、犠（新字体）の異体字（旧字体）
  犧,
  # 覺は、覚（新字体）の異体字（旧字体）
  覺,
  # 屬は、属（新字体）の異体字（旧字体）
  屬,
  # 驅は、駆（新字体）の異体字（旧字体）
  驅,
  # 鷄は、鶏（新字体）の異体字（旧字体）
  鷄,
  # 鐵は、鉄（新字体）の異体字（旧字体）
  鐵,
  # 續は、続（新字体）の異体字（旧字体）
  續,
  # 櫻は、桜（新字体）の異体字（旧字体）
  櫻,
  # 權は、権（新字体）の異体字（旧字体）
  權,
  # 欄は、欄（新字体）の異体字（旧字体）
  欄,
  # 攝は、摂（新字体）の異体字（旧字体）
  攝,
  # 辯は、弁（新字体）の異体字（旧字体）
  辯,
  # 歡は、歓（新字体）の異体字（旧字体）
  歡,
  # 鑄は、鋳（新字体）の異体字（旧字体）
  鑄,
  # 臟は、臓（新字体）の異体字（旧字体）
  臟,
  # 聽は、聴（新字体）の異体字（旧字体）
  聽,
  # 讀は、読（新字体）の異体字（旧字体）
  讀,
  # 竊は、窃（新字体）の異体字（旧字体）
  竊,
  # 響は、響（新字体）の異体字（旧字体）
  響,
  # 疊は、畳（新字体）の異体字（旧字体）
  疊,
  # 穰は、穣（新字体）の異体字（旧字体）
  穰,
  # 覽は、覧（新字体）の異体字（旧字体）
  覽,
  # 戀は、恋（新字体）の異体字（旧字体）
  戀,
  # 驗は、験（新字体）の異体字（旧字体）
  驗,
  # 纖は、繊（新字体）の異体字（旧字体）
  纖,
  # 體は、体（新字体）の異体字（旧字体）
  體,
  # 驛は、駅（新字体）の異体字（旧字体）
  驛,
  # 變は、変（新字体）の異体字（旧字体）
  變,
  # 巖は、巌（新字体）の異体字（旧字体）
  巖,
  # 鑛は、鉱（新字体）の異体字（旧字体）
  鑛,
  # 顯は、顕（新字体）の異体字（旧字体）
  顯,
  # 罐は、缶（新字体）の異体字（旧字体）
  罐,
  # 髓は、髄（新字体）の異体字（旧字体）
  髓,
  # 艷は、艶（新字体）の異体字（旧字体）
  艷,
  # 靈は、霊（新字体）の異体字（旧字体）
  靈,
  # 讓は、譲（新字体）の異体字（旧字体）
  讓,
  # 釀は、醸（新字体）の異体字（旧字体）
  釀,
  # 觀は、観（新字体）の異体字（旧字体）
  觀,
  # 囑は、嘱（新字体）の異体字（旧字体）
  囑,
  # 鹽は、塩（新字体）の異体字（旧字体）
  鹽,
  # 蠻は、蛮（新字体）の異体字（旧字体）
  蠻,
  # 廳は、庁（新字体）の異体字（旧字体）
  廳,
  # 灣は、湾（新字体）の異体字（旧字体）
  灣,
  # 蠶は、蚕（新字体）の異体字（旧字体）
  蠶,
]

# 類似文字
# TODO: 説明なんとかして
# - 見た目が似ている分類が難しい文字をグループごとに定義
# - 各グループは[parent]文字のみ学習させ、[childs]文字列は学習から除外します。
# - [childs]を除いた[parent]のみを学習させることで精度の安定化を図ります。
# - [childs]を[parent]のラベルで学習させるより、[childs]を除外して[parent]のみで学習させた方が精度が安定しました。
# - [childs]は識字不可なためBERTのMLMで解決しています。
similar_character_groups: [
  {
    # カタカナのろ
    parent: "ロ",
    # 漢字のくち
    childs: ["口"],
  },
  {
    # 長音符
    parent: "ー",
    # 漢字のいち
    # ハイフンの全角と記号のマイナス
    # ダッシュ記号
    childs: ["一", "－", "―"],
  },
  {
    # カタカナのか
    parent: "カ",
    # 漢字のちから
    childs: ["力"],
  },
  {
    # カタカナのえ
    parent: "エ",
    # 漢字のこう
    childs: ["工"],
  },
  {
    # ひらがなのへ
    parent: "へ",
    # カタカナのへ
    childs: ["ヘ"],
  },
  {
    # ひらがなのべ
    parent: "べ",
    # カタカナのべ
    childs: ["ベ"],
  },
  {
    # ひらがなのぺ
    parent: "ぺ",
    # カタカナのペ
    childs: ["ペ"],
  },
  # NOTE: 微妙に似ている
  #{
  #  # 全角数字の０
  #  parent: "０",
  #  # 大文字の全角英字Ｏ
  #  childs: ["Ｏ"],
  #},
  {
    # カタカナのに
    parent: "ニ",
    # 漢数字のに
    childs: ["二"],
  },
  # NOTE: 微妙に似ている
  #{
  #  # 漢数字のじゅう
  #  parent: "十",
  #  # 記号のプラス
  #  childs: ["＋"],
  #},
  # NOTE: 微妙に似ている
  #{
  #  # 小文字の全角英字ｘ
  #  parent: "ｘ",
  #  # 記号のバツ
  #  childs: ["×"],
  #},
  {
    # 大文字英字Ｘ
    parent: "Ｘ",
    # ローマ数字Ⅹ (環境依存文字)
    childs: ["Ⅹ"],
  },
  {
    # 大文字英字Ｖ
    parent: "Ｖ",
    # ローマ数字Ⅴ (環境依存文字)
    childs: ["Ⅴ"],
  },
]

# 生成文字
# - ※恋愛ADVは基本全角文字のため半角文字の指定は禁止
# - 生成文字の指定方法は以下のとおり
# -- 文字列の指定
# -- 指定されたテキストファイル(.txt)に含まれる文字列
# -- 指定されたディレクトリに配置された code.txt に含まれる1文字 画像文字対応)
character_parameters: [
  # ひらがな（濁音と半濁音を除く）
  あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわゐゑをん,

  # ひらがな小文字
  ぁぃぅぇぉっゃゅょゎゕゖ,

  # ひらがな（濁音と半濁音のみ）
  がぎぐげござじずぜぞだぢづでどばびぶべぼゔぱぴぷぺぽ,

  # カタカナ（濁音と半濁音を除く）
  アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヰヱヲン・ー,

  # カタカナ小文字
  ァィゥェォッャュョヮヵヶ,

  # カタカナ（濁音と半濁音のみ）
  ガギグゲゴザジズゼゾダヂヅデドバビブベボヴヷヸヹヺパピプペポ,

  # 数字
  ０１２３４５６７８９ ① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ Ⅹ,

  # 英字（大文字）
  ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ,

  # 英字（小文字）
  ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ,

  # 記号など
  ＄￥＋－―＠；：％＆＝’‘／！？、。…※＊＃“”～♪゛「」【】『』［］≦≧《》｛｝＜＞（）÷×☆★◇◆△▲▽▼□■○●↑↓→←．π㎝α℃々,

  # 常用漢字
  ..\resources\codes\常用漢字.txt,

  # 常用外漢字（人名用漢字）
  ..\resources\codes\常用外漢字（人名用漢字）.txt,

  # 常用外漢字（人名用漢字以外）
  ..\resources\codes\常用外漢字（人名用漢字以外）.txt,

  # ハートマーク
  ..\resources\codes\mtlmr3m\heart,
]
