# データセット生成に使用するプロセス数
max_workers: -1

# デバッグの有効性
is_debug_enabled: True

# tqdmの有効性
is_tqdm_enabled: True

# データセットの出力先のディレクトリ
output_directory: ..\resources\datasets\coatnet\mtlmr3m

# フォントとフォントサイズ
font_path: ..\resources\fonts\mtlmr3m\mtlmr3m.ttf
font_size_list: [22, 26, 30, 34, 38, 42]

# 文字情報のパス
# - 生成する文字列や画像文字、除外する文字やラベル値の情報が詰まっています。
character_database_path: ..\resources\labels\mtlmr3m.cdb

# 余白サイズ
# 最小幅、最大幅、ステップ幅
padding_min: 0
padding_max: 2
padding_step: 2

# 文字描画位置のオフセット幅
character_offset_step: 2

# ブラーバリエーションを作成するフォントサイズ
font_size_to_apply_blur: 42
